export const MOSAIC_DATABASE = {
  id: 'life_tracker',
  name: 'Life Tracker',
  enabled: true,
};

const ownerTable = (id, name, columns, indexes = []) => ({
  id,
  name,
  permissions: id === 'friendships' ? [] : ['create("users")'],
  rowSecurity: true,
  enabled: true,
  columns,
  indexes,
});

// Pre-foundation placeholders still exist in production but are intentionally
// excluded from fresh backends and active runtime ownership.
export const MOSAIC_LEGACY_TABLE_IDS = [
  'routines',
  'stickers',
  'analytics_events',
];

export const MOSAIC_TABLES = [
  ownerTable('tasks', 'tasks', [
    { key: 'title', type: 'varchar', size: 255, required: true },
    { key: 'is_completed', type: 'boolean', required: false, default: false },
    { key: 'category_id', type: 'varchar', size: 255, required: true },
    { key: 'order', type: 'integer', required: false, default: 0 },
    { key: 'tags', type: 'varchar', size: 1000, required: false },
    { key: 'date', type: 'varchar', size: 50, required: true },
    { key: 'memo', type: 'varchar', size: 2000, required: false },
    { key: 'image', type: 'longtext', required: false },
    { key: 'created_at', type: 'varchar', size: 50, required: true },
    { key: 'completed_at', type: 'varchar', size: 50, required: false },
    { key: 'updated_at', type: 'varchar', size: 50, required: true },
    { key: 'source', type: 'varchar', size: 50, required: false },
    { key: 'user_id', type: 'varchar', size: 255, required: true },
    { key: 'deleted', type: 'boolean', required: false, default: false },
    { key: 'visibility', type: 'varchar', size: 50, required: true },
    { key: 'routine_id', type: 'varchar', size: 255, required: false },
    { key: 'reminder_time', type: 'varchar', size: 50, required: false },
    { key: 'reactions', type: 'text', required: false },
  ]),
  ownerTable('categories', 'categories', [
    { key: 'name', type: 'varchar', size: 100, required: true },
    { key: 'color', type: 'varchar', size: 20, required: true },
    { key: 'order', type: 'integer', required: true },
    { key: 'visibility', type: 'varchar', size: 50, required: true },
    { key: 'user_id', type: 'varchar', size: 255, required: true },
    { key: 'deleted', type: 'boolean', required: false, default: false },
    { key: 'icon', type: 'varchar', size: 10, required: false },
    { key: 'updated_at', type: 'varchar', size: 50, required: false },
  ]),
  ownerTable('diary', 'diary', [
    { key: 'date', type: 'varchar', size: 50, required: true },
    { key: 'content', type: 'longtext', required: false },
    { key: 'visibility', type: 'varchar', size: 50, required: true },
    { key: 'user_id', type: 'varchar', size: 255, required: true },
    {
      key: 'created_at',
      type: 'varchar',
      size: 50,
      required: false,
      default: '',
    },
    { key: 'updated_at', type: 'varchar', size: 50, required: true },
    { key: 'deleted', type: 'boolean', required: false, default: false },
  ]),
  ownerTable('settings', 'settings', [
    { key: 'user_id', type: 'varchar', size: 255, required: true },
    { key: 'key', type: 'varchar', size: 100, required: true },
    { key: 'value', type: 'longtext', required: true },
    { key: 'deleted', type: 'boolean', required: false, default: false },
    { key: 'updated_at', type: 'varchar', size: 50, required: false },
  ]),
  ownerTable(
    'friendships',
    'Friendships',
    [
      { key: 'user_id', type: 'varchar', size: 255, required: true },
      { key: 'friend_id', type: 'varchar', size: 255, required: true },
      { key: 'friend_username', type: 'varchar', size: 50, required: false, default: '' },
      { key: 'friend_display_name', type: 'varchar', size: 100, required: false, default: '' },
      { key: 'friend_avatar_file_id', type: 'varchar', size: 255, required: false, default: '' },
      { key: 'status', type: 'varchar', size: 30, required: true },
      { key: 'created_at', type: 'varchar', size: 50, required: false, default: '' },
      { key: 'updated_at', type: 'varchar', size: 50, required: false, default: '' },
      { key: 'deleted', type: 'boolean', required: false, default: false },
      { key: 'friend_bio', type: 'varchar', size: 300, required: false },
    ],
    [
      { key: 'idx_user_status', type: 'key', attributes: ['user_id', 'status'] },
      { key: 'idx_user_id', type: 'key', attributes: ['user_id'] },
      { key: 'idx_friend_id', type: 'key', attributes: ['friend_id'] },
    ]
  ),
  {
    id: 'profiles',
    name: 'Profiles',
    permissions: ['create("users")', 'read("users")'],
    rowSecurity: true,
    enabled: true,
    columns: [
      { key: 'user_id', type: 'varchar', size: 255, required: true },
      { key: 'username', type: 'varchar', size: 50, required: true },
      { key: 'display_name', type: 'varchar', size: 100, required: false, default: '' },
      { key: 'avatar_file_id', type: 'varchar', size: 255, required: false, default: '' },
      { key: 'bio', type: 'varchar', size: 300, required: false, default: '' },
      { key: 'is_searchable', type: 'boolean', required: false, default: true },
      { key: 'created_at', type: 'varchar', size: 50, required: false, default: '' },
      { key: 'updated_at', type: 'varchar', size: 50, required: false, default: '' },
      { key: 'deleted', type: 'boolean', required: false, default: false },
    ],
    indexes: [
      { key: 'idx_username_unique', type: 'unique', attributes: ['username'] },
      { key: 'idx_user_id_unique', type: 'unique', attributes: ['user_id'] },
      { key: 'idx_username_key', type: 'key', attributes: ['username'] },
    ],
  },
  ownerTable(
    'messages',
    'Messages',
    [
      { key: 'user_id', type: 'varchar', size: 255, required: true },
      { key: 'thread_id', type: 'varchar', size: 50, required: true },
      { key: 'sender_id', type: 'varchar', size: 255, required: true },
      { key: 'recipient_id', type: 'varchar', size: 255, required: true },
      { key: 'direction', type: 'varchar', size: 20, required: true },
      { key: 'content', type: 'varchar', size: 4000, required: false, default: '' },
      { key: 'task_ref_id', type: 'varchar', size: 255, required: false, default: '' },
      { key: 'task_ref_title', type: 'varchar', size: 500, required: false, default: '' },
      { key: 'task_ref_date', type: 'varchar', size: 50, required: false, default: '' },
      { key: 'task_ref_color', type: 'varchar', size: 20, required: false, default: '' },
      { key: 'read_at', type: 'varchar', size: 50, required: false, default: '' },
      { key: 'delivery_status', type: 'varchar', size: 20, required: false, default: 'delivered' },
      { key: 'created_at', type: 'varchar', size: 50, required: false, default: '' },
      { key: 'updated_at', type: 'varchar', size: 50, required: false, default: '' },
      { key: 'deleted', type: 'boolean', required: false, default: false },
      { key: 'reply_to_id', type: 'varchar', size: 255, required: false },
      { key: 'reply_to_content', type: 'varchar', size: 300, required: false },
      { key: 'reply_to_sender_id', type: 'varchar', size: 255, required: false },
      { key: 'is_unsent', type: 'boolean', required: false },
      { key: 'original_message_id', type: 'varchar', size: 255, required: false },
      { key: 'reactions', type: 'varchar', size: 5000, required: false },
    ],
    [
      {
        key: 'idx_user_thread_created',
        type: 'key',
        attributes: ['user_id', 'thread_id', 'created_at'],
      },
      { key: 'idx_user_deleted', type: 'key', attributes: ['user_id', 'deleted'] },
      { key: 'idx_thread_created', type: 'key', attributes: ['thread_id', 'created_at'] },
      { key: 'idx_sender_id', type: 'key', attributes: ['sender_id'] },
      { key: 'idx_recipient_id', type: 'key', attributes: ['recipient_id'] },
    ]
  ),
  {
    id: 'notifications',
    name: 'Notifications',
    permissions: [],
    rowSecurity: true,
    enabled: true,
    columns: [
      { key: 'recipient_id', type: 'varchar', size: 255, required: true },
      { key: 'actor_id', type: 'varchar', size: 255, required: true },
      { key: 'type', type: 'varchar', size: 40, required: true },
      { key: 'task_id', type: 'varchar', size: 255, required: true },
      { key: 'completed_at', type: 'varchar', size: 50, required: true },
      { key: 'occurred_at', type: 'varchar', size: 50, required: true },
      { key: 'read_at', type: 'varchar', size: 50, required: false, default: '' },
      { key: 'created_at', type: 'varchar', size: 50, required: true },
    ],
    indexes: [
      {
        key: 'idx_notification_recipient',
        type: 'key',
        attributes: ['recipient_id'],
      },
      {
        key: 'idx_notification_actor',
        type: 'key',
        attributes: ['actor_id'],
      },
      {
        key: 'idx_notification_recipient_occurred',
        type: 'key',
        attributes: ['recipient_id', 'occurred_at'],
      },
      { key: 'idx_notification_created', type: 'key', attributes: ['created_at'] },
    ],
  },
  {
    id: 'push_subscriptions',
    name: 'Push Subscriptions',
    permissions: [],
    rowSecurity: true,
    enabled: true,
    columns: [
      { key: 'user_id', type: 'varchar', size: 255, required: true },
      { key: 'endpoint', type: 'longtext', required: true },
      { key: 'p256dh', type: 'varchar', size: 512, required: true },
      { key: 'auth', type: 'varchar', size: 255, required: true },
      {
        key: 'expiration_time',
        type: 'varchar',
        size: 50,
        required: false,
        default: '',
      },
      { key: 'enabled', type: 'boolean', required: false, default: true },
      { key: 'include_task_details', type: 'boolean', required: false, default: false },
      { key: 'created_at', type: 'varchar', size: 50, required: true },
      { key: 'updated_at', type: 'varchar', size: 50, required: true },
    ],
    indexes: [
      {
        key: 'idx_push_user',
        type: 'key',
        attributes: ['user_id'],
      },
      {
        key: 'idx_push_user_enabled',
        type: 'key',
        attributes: ['user_id', 'enabled'],
      },
    ],
  },
  {
    id: 'account_deletions',
    name: 'Account Deletions',
    permissions: [],
    rowSecurity: true,
    enabled: true,
    columns: [
      { key: 'user_id', type: 'varchar', size: 255, required: true },
      { key: 'status', type: 'varchar', size: 30, required: true },
      { key: 'phase', type: 'varchar', size: 50, required: true },
      { key: 'attempts', type: 'integer', required: true },
      { key: 'created_at', type: 'varchar', size: 50, required: true },
      { key: 'updated_at', type: 'varchar', size: 50, required: true },
    ],
    indexes: [
      { key: 'idx_deletion_user', type: 'unique', attributes: ['user_id'] },
      { key: 'idx_deletion_status', type: 'key', attributes: ['status'] },
    ],
  },
];

export const MOSAIC_BUCKET = {
  id: 'task_images',
  name: 'task_images',
  // Reads are granted per file. A bucket-wide read would bypass file security
  // and expose every attachment to every authenticated user.
  permissions: ['create("users")'],
  fileSecurity: true,
  enabled: true,
  maximumFileSize: 5_000_000,
  allowedFileExtensions: ['jpg', 'png', 'gif', 'jpeg', 'webp', 'heic', 'heif'],
  compression: 'none',
  encryption: true,
  antivirus: true,
  transformations: true,
};

export const MOSAIC_BROWSER_ENV = {
  databaseId: MOSAIC_DATABASE.id,
  bucketId: MOSAIC_BUCKET.id,
  tables: Object.fromEntries(MOSAIC_TABLES.map((table) => [table.id, table.id])),
};

export const BOOTSTRAP_API_KEY_SCOPES = [
  'project.read',
  'platforms.read',
  'platforms.write',
  'users.read',
  'databases.read',
  'databases.write',
  'tables.read',
  'tables.write',
  'columns.read',
  'columns.write',
  'indexes.read',
  'indexes.write',
  'buckets.read',
  'buckets.write',
  'functions.read',
  'functions.write',
];
